# Generated by Django 3.2 on 2021-07-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vidoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ویدیو')),
                ('source', models.FileField(upload_to='videos/')),
                ('url', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
