# Generated by Django 3.2 on 2021-08-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vidoes',
            new_name='Videos',
        ),
    ]
