# Generated by Django 3.2 on 2021-08-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_vidoes_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.CharField(max_length=100, verbose_name='ادرس مقاله')),
                ('thumbnail', models.ImageField(upload_to='images/', verbose_name='تصویر بند انگشتی')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
