# Generated by Django 3.2.6 on 2021-09-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210921_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته بندی')),
                ('status', models.BooleanField(verbose_name='وضعیت تگ')),
                ('slug', models.CharField(max_length=100, verbose_name='اسلاگ تگ')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', '\u200d\u200d\u200d\u200dبیش نویس'), ('p', 'منتشر'), ('d', 'حذف شده')], default='d', max_length=1, verbose_name='وضعیت مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='Art', to='account.Category', verbose_name='دسته بندی'),
        ),
    ]
