# Generated by Django 3.2.7 on 2021-09-28 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210925_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فیلم')),
                ('slug', models.CharField(max_length=100, verbose_name='ادرس فیلم')),
                ('source', models.FileField(null=True, upload_to='', verbose_name='videos/')),
                ('iframe_source', models.CharField(max_length=600, null=True)),
                ('thumbnail', models.ImageField(upload_to='images/', verbose_name='تصویر بند انگشتی')),
                ('status', models.CharField(choices=[('d', '\u200d\u200d\u200d\u200dبیش نویس'), ('p', 'منتشر'), ('d', 'حذف شده')], default='d', max_length=1, verbose_name='وضعیت فیلم')),
                ('puished', models.DateField(default=django.utils.timezone.now, verbose_name='زمان انتشار فیلم')),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(related_name='film', to='account.Category', verbose_name='دسته بندی')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='منتشر کننده :')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
            },
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
