# Generated by Django 3.2.5 on 2021-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210828_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسندگی'),
        ),
    ]
