# Generated by Django 3.2.5 on 2021-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210828_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', '\u200d\u200d\u200d\u200dبیش نویس'), ('p', 'منتشر')], default='d', max_length=1, verbose_name='وضعیت مقاله'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسندگی'),
        ),
    ]
