# Generated by Django 3.2.6 on 2021-09-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210828_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیشنویس')], default='d', max_length=1, verbose_name='وضعیت مقاله'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسندگی'),
        ),
    ]
