# Generated by Django 3.2.5 on 2021-08-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_is_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='user',
            name='writer',
            field=models.CharField(default=False, max_length=100, verbose_name='نویسنده'),
        ),
    ]
