# Generated by Django 3.2.5 on 2021-09-05 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210905_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='puished',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان انتشار مقاله'),
        ),
    ]
