# Generated by Django 3.2.5 on 2021-09-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210830_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='writer',
        ),
    ]
