# Generated by Django 3.2.5 on 2021-09-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210904_1421'),
        ('account', '0006_article_puished'),
        ('account', '0007_remove_user_writer'),
    ]

    operations = [
    ]
